clean, clean, clean

diff --git a/config/mksh/mkshrc b/config/mksh/mkshrc
--- a/config/mksh/mkshrc
+++ b/config/mksh/mkshrc
@@ -7,6 +7,27 @@ export LANG=en_US.utf8
 export PATH=$HOME/bin:/sbin:/usr/sbin:$PATH
 export MANPATH=$MANPATH:/usr/local/share/man
 
+PS1='#'                   # Root
+(( USER_ID )) && PS1='$'  # Regular user
+PS1=$'\001\r''${|
+	# Store exit code for later
+	\typeset e=$?
+	\typeset d=${PWD:-?}/
+	\typeset p=~
+	# Replace $HOME with ~
+	[[ $p = ?(*/) ]] || d=${d/#$p\//\~/}
+	d=${d%/}
+	
+	# Hmmm...?
+	\typeset m=${%d} n p=…
+	(( m > 0 )) || m=${#d}
+	(( m > (n = (COLUMNS/3 < 7 ? 7 : COLUMNS/3)) )) && d=${d:(-n)} || p=
+	REPLY+="[$p$d]"
+	# Add exit code
+	(( e )) && REPLY+=" $e "
+	\return $e
+}'"$PS1 "
+
 case "$-" in *i*)
 	# interative mode settings
 
@@ -16,8 +37,6 @@ case "$-" in *i*)
 	HISTFILE=$HOME/.mksh_history
 
 	export EDITOR=vim
-
-	PS1=$'\e[32m${PWD/#$HOME/~}\e[31m${?/#0/}\e[0m\n$ '
 
 	alias ls='ls --color'
 	alias t='tmux attach -t - || tmux new -s -'
